patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      1.8,9.5,0.0,
      1.14,1.83,0.0,
      5.85, 2.0, 0.0,
      5.85, -9.0, 0.0,
      0.0,-8.32, 0.0,
      -3.58,-8.5, 0.0,
      -3.35,9.19, 0.0,
      ]